# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'intfr', 'is_cat', 'classify_img']

# %% ../app.ipynb 1
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

# %% ../app.ipynb 3
learn = load_learner('model.pkl')

# %% ../app.ipynb 5
categories = ('Dog', 'Cat')
def classify_img(img):
    pred, idx, prob = learn.predict(img)
    return dict(zip(categories, map(float, prob)))

# %% ../app.ipynb 7
image = gr.inputs.Image(shape=(192, 192))
label = gr.outputs.Label()
examples = ['dog.jpg', 'dog-cat.jpg', 'cat.jpg']
intfr = gr.Interface(fn=classify_img, inputs=image, outputs=label, examples=examples)
intfr.launch(inline=False)
